### ISSUE TITLE
Progress Bar isn't automatically loading on IDE Startup

### ISSUE THREAD

**Issue by JeremyBouchard220** [christopherosthues/starwars-progress-bar#123]
**Steps to reproduce:**

1. Start IDE
2. Install progress bar plugin
3. Save changes
4. Restart IDE

**Expected behavior:**

- The custom progress bar is loaded and displayed.

**Actual behavior:**

- The default IDE progress bar is displayed.

**Work Around:**

- Disable and Enable the plugin upon the startup of your browser

**Environment:**

- IntelliJ IDEA Ultimate 2023.3.2

**Effected plugin version:**

- 1.11.1

**Comment by JeremyBouchard220** [comment]
I believe the issue has been solved with the update to both IntelliJ IDEA Ultimate 2023.3.3 and Plugin version 1.11.2. I can confirm over the rest of the day and close this out tomorrow or if you'd like me to just close it now I can do that too.

**Comment by christopherosthues** [comment]
You are welcome to confirm it and you can then close the ticket 😃

**Comment by JeremyBouchard220** [comment]
Everything is looking good! Closing this out :)
